"""update slideshow table

Revision ID: 106e8ea3e991
Revises: 75d68b8a4ae9
Create Date: 2019-01-15 11:58:46.619195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106e8ea3e991'
down_revision = '75d68b8a4ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slide_show', sa.Column('images', sa.JSON(), nullable=True))
    op.drop_column('slide_show', 'image1')
    op.drop_column('slide_show', 'image2')
    op.drop_column('slide_show', 'image3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slide_show', sa.Column('image3', sa.BLOB(), nullable=True))
    op.add_column('slide_show', sa.Column('image2', sa.BLOB(), nullable=True))
    op.add_column('slide_show', sa.Column('image1', sa.BLOB(), nullable=True))
    op.drop_column('slide_show', 'images')
    # ### end Alembic commands ###
