"""apk table

Revision ID: 1da27afb0408
Revises: f4953b515686
Create Date: 2019-01-21 17:02:36.390925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da27afb0408'
down_revision = 'f4953b515686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('download_url', sa.String(length=200), nullable=False),
    sa.Column('apk_size', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apk')
    # ### end Alembic commands ###
