"""aboutus

Revision ID: 2d13b9e19733
Revises: b326bd05ba52
Create Date: 2019-01-05 11:14:39.845463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d13b9e19733'
down_revision = 'b326bd05ba52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aboutus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appid', sa.String(length=200), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('editer', sa.String(length=200), nullable=False),
    sa.Column('edit_time', sa.DATETIME(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aboutus')
    # ### end Alembic commands ###
