"""update table apk

Revision ID: 365fade87bea
Revises: 1da27afb0408
Create Date: 2019-01-22 09:52:25.201042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365fade87bea'
down_revision = '1da27afb0408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
