"""update table apk

Revision ID: 5930c7772444
Revises: 365fade87bea
Create Date: 2019-01-22 10:13:51.733627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5930c7772444'
down_revision = '365fade87bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apk', sa.Column('version_name', sa.String(length=200), nullable=False))
    op.add_column('apk', sa.Column('version_number', sa.Integer(), nullable=False))
    op.drop_column('apk', 'version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apk', sa.Column('version', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('apk', 'version_number')
    op.drop_column('apk', 'version_name')
    # ### end Alembic commands ###
