"""201901100955

Revision ID: 75d68b8a4ae9
Revises: f25fa14b089b
Create Date: 2019-01-10 10:38:02.983459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d68b8a4ae9'
down_revision = 'f25fa14b089b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback_name', sa.String(length=40), nullable=True),
    sa.Column('feedback_content', sa.Text(), nullable=True),
    sa.Column('feedback_status', sa.String(length=5), nullable=True),
    sa.Column('edit_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('help_information',
    sa.Column('hi_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.Column('edit_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('hi_id')
    )
    op.create_table('protocol',
    sa.Column('protocol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_name', sa.String(length=40), nullable=True),
    sa.Column('protocol_content', sa.Text(), nullable=True),
    sa.Column('protocol_status', sa.String(length=5), nullable=True),
    sa.Column('edit_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('protocol_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol')
    op.drop_table('help_information')
    op.drop_table('feedback')
    # ### end Alembic commands ###
