"""message 02

Revision ID: 7e4f51f27b36
Revises: 5d0033c8ddb5
Create Date: 2019-01-05 17:41:32.774879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4f51f27b36'
down_revision = '5d0033c8ddb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('msg_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'msg_name')
    # ### end Alembic commands ###
