"""message 03

Revision ID: 82706ecf2a23
Revises: 7e4f51f27b36
Create Date: 2019-01-05 17:42:01.992550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82706ecf2a23'
down_revision = '7e4f51f27b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
