"""Message 01081000

Revision ID: cbd6792f23f5
Revises: 82706ecf2a23
Create Date: 2019-01-08 10:00:15.119231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd6792f23f5'
down_revision = '82706ecf2a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
