"""length

Revision ID: f4953b515686
Revises: 106e8ea3e991
Create Date: 2019-01-16 16:25:39.346951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4953b515686'
down_revision = '106e8ea3e991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
